export const VENUE_PHOTOS: "VENUE_PHOTOS" = "VENUE_PHOTOS";
export const VENUE_PHOTOS_SUCCESS: "VENUE_PHOTOS_SUCCESS" =
  "VENUE_PHOTOS_SUCCESS";
export const VENUE_PHOTOS_FAIL: "VENUE_PHOTOS_FAIL" = "VENUE_PHOTOS_FAIL";
