// export const CLIENT_ID = "DZEQOEKD0XDQM5QRGG25FMDSZC05AZLEXQR5HCLTAKGETEAA";
// export const CLIENT_SECRET = "X4MLA1C5XBEZFOQAYQELZ3QNET5CJOL2IUHGOSRC2CHNOUO5";

export const CLIENT_ID = "5BN1BRUYVWKHUZWNFCUXBNS5LQWO2SDOLOVOWENTYKZ5ARXU";
export const CLIENT_SECRET = "ITAWSJXNZ2FFCXUQNVH4SBDDZZNKSDL12OWQGBZ1W3WRJKIV";

export const LAT = 51.552841;
export const LNG = 0.20067138999999656;

export let USE_FAKE_DATA = process.env.NODE_ENV === "test" ? true : false;
export const UseFakeData = (status: boolean) => {
  USE_FAKE_DATA = status;
};
